### PR TITLE
Added OpenLitterMap.yarn

### PR DESCRIPTION
**Pull request by xlcrr**
Added OpenLitterMap.yarn

OpenLitterMap.com empowers and incentivises anyone to map and share open data on plastic pollution anywhere

See
https://opengeospatialdata.springeropen.com/articles/10.1186/s40965-018-0050-y

### CODE REVIEW

**Comment by xlcrr** [comment]
Hi @jflasher do you mean OpenLitterMap or the .yarn file?

OpenLitterMap is a work in progress, I guess therefore the yarn file is a WIP too !

**Comment by jflasher** [comment]
@xlcrr fair enough! Basically, just wondering if you want us to review the .yaml file now or if you are intending to make changes before you would like to see it merged? In particular, it looks like the data is not yet accessible in the bucket provided `olm-s3` so we would not be able to merge this in currently.

**Comment by xlcrr** [comment]
Ah ok, I see what you mean now. "olm-s3" is the bucket where the images are being hosted.

For example 

https://olm-s3.s3.eu-west-1.amazonaws.com/984/q4HQ9zx34hwgChPoJnwN7k9CJMKw4FaXur57umNH.jpeg

To download the data, simply finish any url with /download

For example, 

openlittermap.com/maps/Ireland/download

openlittermap.com/maps/UK/England/download

openlittermap.com/maps/Australia/NSW/Sydney/download

How do you advise we proceed?

**Comment by xlcrr** [comment]
Hi again and thanks 

The available data updates dynamically based on user generated input and it doesn't make sense for me to keep CSV data in s3 at this point although that might be an option in the future once we have more historical data.

I am also just a 1 man team teaching myself how to code so resources and options are limited. For more info you can refer to the paper I linked above and if you think it can make a use case for open data on AWS I'd love to help with that.

**Comment by jflasher** [comment]
Closing this for now as it doesn't meet the goal of listing data available via native AWS services. If that changes in the future, please feel free to reopen.

**Pull request closed without merging**
