### PR TITLE
Change name and citation for OpenFold dataset

### PR DESCRIPTION
**Pull request by gahdritz**
We just released our manuscript & would like to update the RODA entry to reflect that.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by chueatwork** [comment]
Congratulations @gahdritz ! Would you also like to add the publication as a DataAtWork entry? Stanza and fields below (AuthorURL is optional):

```
DataAtWork:
  Publications:
    - Title:
      URL:
      AuthorName:
      AuthorURL: 
```

**Comment by gahdritz** [comment]
Also, should this replace the "Citation" field?

**Comment by chueatwork** [comment]
Hi @gahdritz the AuthorName field is free text so will accept anything, but our guidelines recommend that you use scientific citation style Last Name, First Initial; Last Name2, First Initial 2; etc... and to stop at 6 authors if there are more than 6. I think since you want folks citing your publication, you shouldn't change the Citation field, just add the DataAtWork stanza!

**Comment by gahdritz** [comment]
@chueatwork I added the entry. Is the author list right, or is there something I can add to indicate that there are actually more than 6 authors?

**Comment by chueatwork** [comment]
@gahdritz I added an "et al" to the end but if you want to add the full author list you are welcome to; I think the more important thing is to have the publication URL =)

**Comment by gahdritz** [comment]
Ok LGTM.

**Pull request merged**
