### PR TITLE
Update qiime2.yaml

### PR DESCRIPTION
**Pull request by gregcaporaso**
*Issue #, if available:* Not applicable. 

*Description of changes:* Long-overdue update to information on front-facing *Registry of Open Data on AWS* page.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by berylrab — CHANGES_REQUESTED** [review]
Hi Greg, the changes look good. Please add the following tags as well so data consumers can find this dataset: "life sciences" and "microbiome". Thank you for keeping the dataset up to date.

**Comment by gregcaporaso** [comment]
Hi @berylrab, thanks for the suggestion. I updated the tags in the most recent commit - "microbiome" was already in there, but I added "life sciences" and "metagenome" and removed a couple of the less relevant ones.

**Review by berylrab — CHANGES_REQUESTED** [review]
Thanks Greg, could you change the "metagenome" tag to "metagenomics" please? We have a list of tags here that we try to use so that all the datasets are using the same tags (https://github.com/awslabs/open-data-registry/blob/main/tags.yaml).

**Comment by gregcaporaso** [comment]
Done - sorry about that @berylrab!

**Pull request merged**
