### PR TITLE
Update publications in spartan-cloud registry

### PR DESCRIPTION
**Pull request by Haihui-Zhu**
*Issue #, if available:*

*Description of changes:*
Adding two more representation publications. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
Please rebase your branch or give us the ability to do it for you!

**Comment by Haihui-Zhu** [comment]
what about now?

**Comment by cstner** [comment]
Good to go!

**Comment by Haihui-Zhu** [comment]
Thanks!

**Pull request merged**
