### PR TITLE
Tracking the sun

### PR DESCRIPTION
**Pull request by digitalrager**
Submitting a the new Tracking the Sun from NREL on behalf of Lawrence Berkeley National Laboratory (LBNL) dataset for consideration in the April release. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by digitalrager** [comment]
Couldn't see details on why this is failing checks.  Will wait for guidance.  Thanks!

**Comment by zflamig** [comment]
You should be able to see the Travis checks once they complete. They often take a lot longer to start running. In this case the error is `('Invalid tag!', 'photovoltaic')`

The tags need to match ones listed in https://github.com/awslabs/open-data-registry/blob/master/tags.yaml and you can also add new tags for any you feel strongly about.

**Comment by zflamig** [comment]
@digitalrager Can you update against master and then we can merge? Thanks!

**Comment by zflamig** [comment]
@digitalrager Just wanted to check again if you can update this branch to be in line with the base branch? You should be able to push the button to update on github. Thanks!

**Pull request merged**
