### PR TITLE
Initialize cellpainting-gallery on RODA

### PR DESCRIPTION
**Pull request by shntnu**
- [x] Follow instructions here https://github.com/awslabs/open-data-registry/blob/main/README.md

----

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: afce1598ab597f10cf72c8188054f3aeab0c0eb9
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=75ddebd4-a6a3-44da-a72b-bf33159669bb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by chueatwork** [comment]
Hi @shntnu hope all is well, just checking in to see how this YAML is progressing! Let me know if you need help.

**Comment by shntnu** [comment]
Hi @chueatwork! We're getting pretty close to the first release of a subset (https://openreview.net/forum?id=DlCpTuf5SGy&noteId=A-fcv9O1q79). @niranjchandrasekaran is gearing up to upload all the data from that paper to the bucket and we will tag you to review this PR

**Comment by shntnu** [comment]
@chueatwork I have a first draft ready

There's a lot more to do 

- [ ] I have created a stub for our documentation repo https://github.com/broadinstitute/cellpainting-gallery but there's nothing in there yet. It might eventually look like https://bbbc.broadinstitute.org/ but we will need to start small, with maybe just a TOC for the datasets to start with?
- [ ] More Tools & Applications – Distributed-CellProfiler, DeepProfiler, profiling-recipe, amongst other
- [ ] More Tutorials – profiling-handbook, forum.image.sc, CellProfiler videos that are profiling-centric, relevant blog posts
- [ ] More Publications – the six publications listed in http://broad.io/profiling_dataset, but many ones. It might not be practical to keep this item updated because we will be duplicating the effort (because we are committed to maintaining http://broad.io/profiling_dataset); tbd
- [ ] What else?

Can you let me know what are the crucial things we should get done before publishing this on the registry? Feel free to add to the list

Meanwhile, I'll also tag @AnneCarpenter in case she'd like to edit https://github.com/awslabs/open-data-registry/blob/3def95323c18b2808b4474256312f90d545e330c/datasets/cellpainting-gallery.yml (instructions are at https://github.com/awslabs/open-data-registry/blob/main/README.md)

**Comment by chueatwork** [comment]
Thanks @shntnu ! This is a great start. I think for us to publish we'll want to flesh out the documentation--basically what each dataset is and how to get to it (ergo the first item on your checklist). I also agree that a broader and rounded out description will benefit the discoverability of the data on RODA (second item). The remainder can be added over time--but if the goal is to get the data out and in the public, I think only the two items referenced above are necessary!

**Comment by chueatwork** [comment]
Hi @shntnu thanks for pushing this! FYI--the bucket is currently not listable--if I recall, we had discussed an embargo period; can you clarify whether this bucket should be public and if not, when it will be? Thanks!

**Pull request merged**
