### PR TITLE
Add Rwanda yaml

### PR DESCRIPTION
**Pull request by JA2-Mikai**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by JA2-Mikai** [comment]
yaml of ALOS-2/PALSAR-2 Rwanda observation L2.1 uploaded by JAXA has been uploaded.
Please check if the format is correct.

**Review by cstner — CHANGES_REQUESTED** [review]
Need a URL in Line 37

**Comment by JA2-Mikai** [comment]
> 37行目にURLが必要

**Comment by JA2-Mikai** [comment]
raise ScannerError(
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "datasets/palsar-2-scansar-flooding-in-rwanda.yaml", line 4, column 1
could not find expected ':'
  in "datasets/palsar-2-scansar-flooding-in-rwanda.yaml", line 5, column 1
palsar-2-scansar-flooding-in-rwanda.yaml failed validation

[Container] 2023/05/17 10:20:25 Command did not exit successfully bash _scripts/test.sh exit status 123
[Container] 2023/05/17 10:20:25 Phase complete: PRE_BUILD State: FAILED
[Container] 2023/05/17 10:20:25 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: bash _scripts/test.sh. Reason: exit status 123

I don't understand the reason for this error.
Should I reflect the writing style of the sentence that you have corrected?

**Comment by cstner** [comment]
Did you mean to close this Pull Request?  I think we can fix the problem in the yaml if you reopen it

**Pull request closed without merging**
