### PR TITLE
Pasteur Logan: added YAML dataset

### PR DESCRIPTION
**Pull request by rchikhi**
*Description of changes:*

Added a new dataset YAML: Pasteur Logan

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pschmied** [comment]
Hi @rchikhi once the data are staged (perhaps they already are?), please add the ControlledAccess field along with a location of where users can request access. An example can be found: https://github.com/awslabs/open-data-registry/blob/main/datasets/bdsp-hsp.yaml

**Comment by rchikhi** [comment]
hi @pschmied, do we need that field? Our bucket will be public, not controlled access

**Comment by pschmied** [comment]
Hi @rchikhi , no you do not need that tag if the intention is for a public bucket. Once the bucket is made public, we can merge! Please reach out to me via email if you need assistance on the bucket policy.

**Comment by rchikhi** [comment]
Ah I see! good thing you mentioned that, because the bucket URL has since changed, it's not s3://logan but s3://logan-public

**Pull request merged**
