### PR TITLE
PR for SPARTAN data. 

### PR DESCRIPTION
**Pull request by Haihui-Zhu**
*Description of changes:*
Adding yaml file for SPARTAN data.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
Please add a ".yaml" extension to this file and resubmit

**Comment by Haihui-Zhu** [comment]
Added.

**Review by cstner — CHANGES_REQUESTED** [review]
Change line 33 from this:
Title: Elemental Characterization of Ambient Particulate Matter for a Globally Distributed Monitoring Network: Methodology and Implications

to this:
Title: "Elemental Characterization of Ambient Particulate Matter for a Globally Distributed Monitoring Network: Methodology and Implications"

**Comment by Haihui-Zhu** [comment]
> Change line 33 from this: Title: Elemental Characterization of Ambient Particulate Matter for a Globally Distributed Monitoring Network: Methodology and Implications
> 
> to this: Title: "Elemental Characterization of Ambient Particulate Matter for a Globally Distributed Monitoring Network: Methodology and Implications"

Updated all three titles.

**Review by cstner — CHANGES_REQUESTED** [review]
Hi there - please remove any tags such as "ambient particulate matter" that aren't already in the tags.yaml here: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml

**Comment by Haihui-Zhu** [comment]
> Hi there - please remove any tags such as "ambient particulate matter" that aren't already in the tags.yaml here: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml

Done.

**Review by cstner — CHANGES_REQUESTED** [review]
Two more things:
1/ lines 17-20 cannot be unknown, but if you haven't gotten to that step yet in the onboarding guide, just lease this Pull Request until you have run the CloudFormation template and have these values.
2/ once you have filled in these values, please update your branch or allow us to update your branch for you!

**Comment by Haihui-Zhu** [comment]
lines 17-20 updated. Branch up-to-date. I didn't see how I can allow you to update the branch.

**Comment by cstner** [comment]
sorry I was out of the office - can you update on more time and I'll merge it?

**Comment by Haihui-Zhu** [comment]
done.

**Pull request merged**
