### PR TITLE
Add datasets/wise-allwise.yaml

### PR DESCRIPTION
**Pull request by troyraen**
*Description of changes:*  Adds the wise-allwise dataset. This is astronomy data from the AllWISE Data Release of the Wide-field Infrared Survey Explorer.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by johnMediaOnFire** [comment]
The handbook mentions that we need a logo and that "Please also send a copy of your logo to be used on the dataset landing page to opendata@amazon.com."

**Comment by johnMediaOnFire** [comment]
Looks like the Description field is 710 characters -- *github* doc says only the first 600 characters will be display on the homepage. As long as you're cool with the cutoff...

**Comment by johnMediaOnFire** [comment]
The Citation section looks inconsistent with what's described in the YAML - maybe worth a second look?

**Comment by troyraen** [comment]
Thank you. I've emailed the logo and updated the Description. As I understand the instructions, the Citation we include here will be appended to the default citation. This is consistent with [HST](https://registry.opendata.aws/hst/).

I have one remaining question about how we're listing the bandpasses, but it will have to wait until folks are back in the office on Monday.

**Comment by troyraen** [comment]
As far as I can tell, an AWS account is not required for access. So I went ahead and added:

`AccountRequired: False`

**Pull request merged**
