### PR TITLE
Adding Datasets for RSNA

### PR DESCRIPTION
**Pull request by ceggers-rsna**
Hi,

I created PR#2141, and I'm not seeing our yaml.

Submitting three additional datasets for your review, and to check if RSNA is published within the Open Data project.

Thanks!

ceggers@rsna.org (Colin)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pschmied** [comment]
Hi @ceggers-rsna , we require pull requests to be fully up to date with upstream before merging. And unfortunately, this repo moves pretty quickly. Any chance you can allow updates from us so we can merge in any upstream changes? That will allow us to merge: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by ceggers-rsna** [comment]
Hi @pschmied , I'm unfortunately not seeing the option you're mentioning.

**Comment by pschmied** [comment]
No worries, @ceggers-rsna — sometimes if you are a member of an organization, the organization will not allow this setting.

I was looking at your pull request and noted that the S3 resources you provided are not correct. Those will need to point to the S3 buckets where you are staging your data. Please reach out to me via email if you have any questions about what should go in there.

**Comment by ceggers-rsna** [comment]
@pschmied ah gotcha! No worries, sorry about that.  Let me get the correct locations committed and included in this PR.

**Comment by pschmied** [comment]
Many thanks, @ceggers-rsna — merging!

**Pull request merged**
