### PR TITLE
Added tags for metadata, RDF, SPARQL

### PR DESCRIPTION
**Pull request by pjotrp**

### CODE REVIEW

**Comment by pjotrp** [comment]
@JervenBolleman you may want to add these to Uniprot.

**Comment by chueatwork** [comment]
@pjotrp please merge upstream changes to your branch and I can then merge this PR, thank you!

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 5029f1f7d41fc3f24ea78402d479a1eaef2aa0ad
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=74bd9e0a-d8b3-49e5-8e74-09ff25184230%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by pjotrp** [comment]
Should be fine to merge.

**Pull request merged**
