### PR TITLE
Adds Kaguya TC Monoscopic Observations

### PR DESCRIPTION
**Pull request by jlaura**
This PR adds ~30,000 JAXA Kaguya/SELENE monoscopic observations of the lunar surface as ARD / COGs.

This is a release in partnership between JAXA/USGS/NASA. Is it possible to get this logoed as such? I am not sure how one might include a new logo.

We will have 2 more related datasets with similar data collected in two different observing modes. Total release will be ~500,000 images.

### CODE REVIEW

**Comment by cstner** [comment]
Hi Jay,  Did you request for this data to be added to the Open Data program?

**Review by cstner — CHANGES_REQUESTED** [review]
Please let me know who you were working with from JAXA, USGS, and NASA on this and if you have submitted a request to add this dataset to the Open Data program

**Comment by jlaura** [comment]
Morning @cstner I have been working with Joe Foster and Steve Crawford  at NASA with all of these data releases. I am from USGS. My JAXA contact is another researcher, who I can link in if needed.

I was not aware of an additional request form to get these released. Would you mind linking? (I checked the README and the CONTRIBUTING docs, but did not see a link.)

Thanks!

**Review by cstner — APPROVED** [review]
Approved by NASA

**Comment by jlaura** [comment]
@cstner Thanks! I have 2 more related JAXA sets to push. Again, working with JAXA on the release and the aforementioned NASA colleagues. 

What can I do to get a JAXA logo added to the registry pages? That is important to our JAXA colleagues as they would like to retain recognition that these data originate from a Japanese funded and directed mission.

**Comment by cstner** [comment]
@jlaura - yes!  Please submit a PR to github.com/awslabs/open-data-registry-browser.  See the README and look for the section on Logos

**Pull request merged**
