### PR TITLE
Added another resource file and edited previous description.

### PR DESCRIPTION
**Pull request by jacklchang**
*Description of changes:*
We have uploaded another zip file to the S3 bucket and we have updated the description to reflect that change.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pschmied** [comment]
Hi @jacklchang ,

Can you allow edits from maintainers per: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I am unable to merge your request as long as your fork is behind the branch that we'd merge into.

**Comment by jacklchang** [comment]
Hi Peter, I don’t see the option to allow edits and access by maintainers:  From: Peter Schmiedeskamp ***@***.***>Date: Thursday, February 15, 2024 at 2:33 PMTo: awslabs/open-data-registry ***@***.***>Cc: Jack Chang ***@***.***>, Mention ***@***.***>Subject: Re: [awslabs/open-data-registry] Added another resource file and edited previous description. (PR #2126)Hi @jacklchang ,Can you allow edits from maintainers per: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-forkI am unable to merge your request as long as your fork is behind the branch that we'd merge into.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jacklchang** [comment]
> Hi @jacklchang ,
> 
> Can you allow edits from maintainers per: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> I am unable to merge your request as long as your fork is behind the branch that we'd merge into.

Following up on this!

**Comment by pschmied** [comment]
Also, @jacklchang  I noticed that there are some duplicate resources listed in this YAML. Typically, we would not recommend listing individual files as resources within an S3 bucket. If all files are within a single S3 bucket, my recommendation would be to collapse those to a single resource entry, and then provide a description of specific files in the documentation.

**Comment by jacklchang** [comment]
> Also, @jacklchang I noticed that there are some duplicate resources listed in this YAML. Typically, we would not recommend listing individual files as resources within an S3 bucket. If all files are within a single S3 bucket, my recommendation would be to collapse those to a single resource entry, and then provide a description of specific files in the documentation.

Thank you for letting me know! I have combined them into one resource entry and information about the individual files are in the documentation.

**Comment by pschmied** [comment]
Thank you! Merged.

**Pull request merged**
