### PR TITLE
EURO-CORDEX

### PR DESCRIPTION
**Pull request by larsbuntemeyer**
closes https://github.com/euro-cordex/cordex-aws/issues/6

Draft PR for preparation of final data workflow.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cstner** [comment]
Hi Lars - this is still a draft so cannot be merged.  Are you ready to submit or is it still a work in progress?

**Comment by larsbuntemeyer** [comment]
Hi @cstner, thanks for looking into this! It is in fact still a draft since i am about to finalize my upload!

**Comment by larsbuntemeyer** [comment]
Hey @cstner, i have finally updated my uploads, tutorials and docs! So this is now ready for review i guess!

**Comment by cstner** [comment]
Hi Lars - please update your branch and then I can review it!

**Comment by larsbuntemeyer** [comment]
Thanks @cstner !

**Pull request merged**
