### PR TITLE
NDVI Anomaly and Climatology Yaml

### PR DESCRIPTION
**Pull request by nanaboamah89**
*Description of changes:*
Added the yaml file for NDVI Anomaly and Climatology.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
Please update your branch or allow us to update it for you!

**Comment by nanaboamah89** [comment]
Hello @cstner, sorry I push the wrong PR. I close this PR and make the necessary amendment and push it to you again. Thank you

**Comment by nanaboamah89** [comment]
> Please update your branch or allow us to update it for you!

@cstner Please kindly update the branch.

**Comment by cstner** [comment]
I can update the branch for you if you enable "Allow edits from maintainers" (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Pull request merged**
