### PR TITLE
initial commit for nasa-soteria-data

### PR DESCRIPTION
**Pull request by tylerfettrow**
*Issue #, if available:*

*Description of changes:*
Initial commit for nasa-soteria-data 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tylerfettrow** [comment]
It's not clear what is wrong with the yaml file.

**Review by cstner — CHANGES_REQUESTED** [review]
Please remove any tags that aren't already listed in the tags.yaml file here: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml   For example, please remove "airtraffic operations".

**Comment by tylerfettrow** [comment]
> Please remove any tags that aren't already listed in the tags.yaml file here: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml For example, please remove "airtraffic operations".

I fixed, the tag, but same error:

raise CoreError(u"Error when running extension function : {0}".format(func))
pykwalify.errors.CoreError: <CoreError: error code 3: Error when running extension function : ext_tags: Path: '/'>
nasa-soteria-data.yaml failed validation

Still not clear what this is referring to. I had the urls without the trailing '/' when I was originally getting this error.

**Review by cstner — CHANGES_REQUESTED** [review]
Check your tags against this file: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml  You can only use tags that are in this file, so for example, you'll need to remove this one: airtraffic operations

**Pull request merged**
