### PR TITLE
Add Capella Space Open SAR Dataset

### PR DESCRIPTION
**Pull request by jason-brown904**
*Issue #, if available:*

*Description of changes:*
Capella SAR Open Data pull request

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jeffejefe** [comment]
@jason-brown904 please rename the file in lower case, consider a simple name e.g. capella_opendata.yaml since that becomes the url slug for the landing page, and change the extension to .yaml (from .yml). Also please send us a high resolution logo (can be .png for now) that I will manually add to the registry. Thanks!

**Comment by jeffejefe** [comment]
@jason-brown904 I ran a quick test to see if everything else was fine. The tests passed if you are ok with the rename I'll merge, otherwise feel free to edit the file name in the same branch.

**Comment by jason-brown904** [comment]
@jeffejefe - that name is good, thanks. Will get the logo today asap.

**Comment by jeffejefe** [comment]
Thanks @jason-brown904

**Pull request merged**
