### PR TITLE
updating publications that reference this dataset

### PR DESCRIPTION
**Pull request by simonrdavies**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pschmied** [comment]
Hi @simonrdavies ,

I notice that the branch you're working on is a lot of revisions behind what's current. I think that may be part of your issue with the test suite. Would you kindly [update your fork / branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)? There isn't a merge conflict because you aren't editing any of the other files that have changed, but the tests are running based on the outdated state of your fork, and are failing due to changes that have happened over time.

**Comment by simonrdavies** [comment]
> Hi @simonrdavies ,
> 
> I notice that the branch you're working on is a lot of revisions behind what's current. I think that may be part of your issue with the test suite. Would you kindly [update your fork / branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)? There isn't a merge conflict because you aren't editing any of the other files that have changed, but the tests are running based on the outdated state of your fork, and are failing due to changes that have happened over time.

. Thanks for the tip. I have re synched my fork and I am trying again. Thanks

**Comment by simonrdavies** [comment]
Hi Peter
Thanks for the mail and the suggestion. I have now resynched my fork and am trying again. Fingers crossed.
While I have you on the line, I was wondering if there is any way I can affect the "How to Cite" text on the page:














On another note, the papers describing this dataset are now being published and I was looking into trying to find a way of either monitoring the traffic to this data set or monoitoring the number/size of downloads (or even ideally both)I have looked a little at storeage lens and also Athena.I was wondering if you could let me know if I am allowed to use any of these tools and if so, would it be possible for you to suggest the best method of viewing this data ?
Best regardsSimon



    On Wednesday, January 26, 2022, 12:31:19 AM GMT+1, Peter Schmiedeskamp ***@***.***> wrote:  
 
 


Hi @simonrdavies ,

I notice that the branch you're working on is a lot of revisions behind what's current. I think that may be part of your issue with the test suite. Would you kindly update your fork / branch? There isn't a merge conflict because you aren't editing any of the other files that have changed, but the tests are running based on the outdated state of your fork, and are failing due to changes that have happened over time.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pschmied** [comment]
Hi Simon, thank you for your update! I'll reach out via email on the other items.

**Pull request merged**
