### PR TITLE
Nsrdb wtk updates

### PR DESCRIPTION
**Pull request by MRossol**
*Issue #, if available:*

*Description of changes:*
This is pull request contains an updated list of the contents in the nrel-pds-nsrdb and nrel-pds-wtk buckets

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 4483c3114adc2dfd198acf7aee304b1e0b8358c0
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c895e408-771d-41a9-bfe3-c66f8480efa6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 18db0382b9196cfcd2ab17a2614cb71e23e970ad
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e3dca2d7-eabb-4ccd-a440-1c8b1b3efa10%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jflasher** [comment]
Hi @MRossol unfortunately it looks like you started from an out of date branch when making these changes and datasets/nrel-pds-nsrdb.yaml is showing a conflict. Would you be able to resolve those conflicts? Thanks!

**Comment by MRossol** [comment]
@jflasher, no problem, conflicts fixed and I updated our fork's master as well.

**Pull request merged**
