### PR TITLE
Add  COAWST forecast archive

### PR DESCRIPTION
**Pull request by rsignell**
*Description of changes:*
Adding the USGS COAWST (Coupled Ocean Atmosphere Wave and Sediment Transport) model archive data of the US East and Gulf Coasts (2009-2022)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
Can you please update your branch or give us permission to do this for you?

**Review by cstner — CHANGES_REQUESTED** [review]
can you please add the aws-pds tag and update one more time? Thanks!

**Comment by rsignell** [comment]
@cstner done!

**Comment by rsignell** [comment]
Well, yes, *now* it's out of date. :)   It wasn't when I added the changes.   So I guess the only reasonable way to do this is to give you commit on the repo?

**Pull request merged**
