### PR TITLE
Adds Europa Image Mosaics

### PR DESCRIPTION
**Pull request by jlaura**
*Issue #, if available:*

*Description of changes:*
Adds NASA Europa controlled image mosaics to the ODR. These are products derived from the currently released individual observations. Minimal changes to the template.

Note: These share a DOI with the observations. It looks like the USGS released both under the same DOI.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

@nasacrawford @jeffejefe

### CODE REVIEW

**Comment by jeffejefe** [comment]
Thanks @jlaura. I had a couple of comments.

1. Should we consider combining the two Europa listings into a single one since the description for https://registry.opendata.aws/nasa-usgs-europa-observations/ is identical?  (see example: https://registry.opendata.aws/pgc-arcticdem/) 
2. If yes, we create a new yaml that is e.g. `nasa-usgs-europa`, list the 2 arns and provide 2 documentation urls.
3. Also good to add the full prefix to each arn e.g.  ARN: arn:aws:s3:::astrogeo-ard/jupiter/europa/galileo_voyager/usgs_controlled_mosaics/

Let me know your thoughts there. We can have 2 dataset listings if it makes sense to keep them separated but it would then be good to provide unique descriptions.

**Comment by jeffejefe** [comment]
Reviewing again, it looks like the descriptions were unique so keeping separate makes sense.

**Comment by jlaura** [comment]
@jeffejefe Sounds good. And yes, they are almost identical. The data individual observations were used to create the mosaics. We were discussing internally about which way was best. Having this merged is terrific! 

Many thanks!

**Comment by jeffejefe** [comment]
Got it so to clarify, there are two separate listings currently. If we want these merged into a single entry then we'll need to update the description to reflect that, create a new yaml with two arns, add the two doc urls and deprecate the old ones. Happy to work with you on that route just let me know. For now they will be as below.

- https://registry.opendata.aws/nasa-usgs-europa-mosaics/
- https://registry.opendata.aws/nasa-usgs-europa-observations/

**Comment by jlaura** [comment]
Perfect! And apologies for my imprecise language. Merging the PR was great. If we decide these should be one ODR listing, I'll open a new Pr.

**Comment by jeffejefe** [comment]
sounds good thanks!

**Pull request merged**
