### PR TITLE
First draft of opencell yaml

### PR DESCRIPTION
**Pull request by keithchev**
*Issue #, if available:*

*Description of changes:*
First draft of the metadata for the OpenCell dataset.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: a9f8b3ee8fa17a982a3a9d0e5be2c5ae6d0dffc2
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d165d9f2-be5a-4fd7-aab3-79ede9f0f45d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 12706ab3d24f14179d82844f80675461759aa2f0
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=891af4fb-2b40-402e-89b6-4d925ef91b82%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by chueatwork** [comment]
@keithchev this looks like a great first start. Just tried listing this S3 bucket and it is publicly listable with just a few prefixes under `public-test`. Is that your intent, or will you revert to an embargoed state for the real data? If we are going to make the data not-public we'll want to add a ControlledAccess tag and then somewhere in the docu state that the data are embargoed until publication.

Other things we could do, if we wanted--we have had some data providers make the data listable but not gettable until publication so that the data user can get familiar with data strucure etc. Alternatively we can make one prefix in the bucket not listable and keep embargoed data in there.

**Comment by keithchev** [comment]
@chueatwork sorry things are in a state of limbo at the moment! I was just sanity-checking that the public bucket works the way I assumed it would (especially using an index.html to display a list of bucket objects in a web browser, without AWS credentials). We are going to make a decision about whether we need to embargo the raw data this week - my feeling and hope and is that we won't need to, but of course it's not up to me. I do like the idea of making the data listable but not gettable until publication. Let me get back to you later this week when we've made a decision, and we can edit the yaml as necessary.

**Comment by chueatwork** [comment]
No worries at all. I won't merge this till we decide on the data embargo then; keep me posted!

Erin

**Comment by keithchev** [comment]
@chueatwork the documentation page on our web portal is now live (at https://opencell.czbiohub.org/download). If everything looks good to you, I think this is ready to be merged.

**Pull request merged**
