### PR TITLE
NapierOne mixed file dataset

### PR DESCRIPTION
**Pull request by simonrdavies**
Original yaml version for NapierOne mixed file dataset

*Issue #, if available:*

*Description of changes:*
 Initial distribution of the yaml for the NapierOne mixed file dataset

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 3010ca7df9ab63bbfaf859ada7d605f5e73026c1
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3e981959-3ade-46ac-8d0f-7e8d6fd8f678%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: e5fda66f20583bdfae281c350021f8e270592c12
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6715f5a1-f684-4a8e-8529-a37743bb1bb6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by simonrdavies** [comment]
I have renamed NapierOne.yaml to napierone.yaml

**Comment by simonrdavies** [comment]
will create a new pull request with the NapierOne.yaml changed to nampierone.yaml

**Pull request closed without merging**
