### PR TITLE
Adding new nex-gddp-cmip6 dataset

### PR DESCRIPTION
**Pull request by vwild1**
*Issue #, if available:* 
N/A

*Description of changes:*
Registering NEX-GDDP-CMIP6 dataset with AWS. There are tags in this file that are not part of the broader tags.yaml, I'd like to request that they be added as well. Let me know if you need any more info!

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jeffejefe** [comment]
@vwild1 can you remove the additional tags that you added to tags.yaml from both the dataset yaml and tags page? We can review the proposal to add them in a separate PR but best to keep them out of this one to allow it to build cleanly. You might consider adding any of those in the description to help search if relevant. You can just go through and undo the changes to tags and then remove from the dataset yaml.

**Comment by vwild1** [comment]
@jeffejefe @jflasher @cstner What's the status of this request? Can I update tags.yaml in the same pull request as the dataset? All the conflicts have been resolved and the check passed. jeffejefe your previous comment is no longer visible.

**Comment by jeffejefe** [comment]
@vwild1 my comment was moved to the relevant section of the file. Best to remove the tag additions from tags.yaml and nex-gddp-cmip6.yaml, then create a new PR. Also it appeared that the index.html used for the browse bucket wasn't available.

**Comment by jeffejefe** [comment]
@vwild1 looks like the commit removed the tags.yaml completely. Can you make sure you have the latest version of tags.yaml prior to making your PR? You can do a git status and remove it from the commit.

**Comment by vwild1** [comment]
@jeffejefe okay the tags have been removed and the file is at the latest version

**Comment by jeffejefe** [comment]
@vwild1 looks good. I made a few changes removing the Browse Bucket until you have the index.html file in place. For reference you could use something like https://github.com/awslabs/aws-js-s3-explorer. Note it's similar to [POWER](https://power-analysis-ready-datastore.s3.us-west-2.amazonaws.com/index.html).

**Comment by jeffejefe** [comment]
@vwild1 for the Data Provider, I removed NCCS because it is broadly NASA providing and do not display multiple logos on the same listing.

**Comment by vwild1** [comment]
@jeffejefe okay. For the index.html, where should that file be uploaded? I've set the permissions like https://github.com/awslabs/aws-js-s3-explorer suggests, but it doesn't seem to describe how to add the index.html file

**Comment by jeffejefe** [comment]
@vwild1 The index.html simply needs to live at the root directory, similar to where it is here:  `aws s3 ls --no-sign-request s3://power-analysis-ready-datastore/`. You should be able to the [AWS Console](https://console.aws.amazon.com/s3) or using the CLI.

**Pull request merged**
