### PR TITLE
Added stoic2021-training yaml

### PR DESCRIPTION
**Pull request by luukboulogne**
*Description of changes:*
Added stoic2021-training documentation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by luukboulogne** [comment]
Temporarily closed this pull request to allow a review of all involved parties.

**Comment by luukboulogne** [comment]
The dataset is ready to be published on the open data registry.

**Comment by chueatwork** [comment]
Hi @luukboulogne thank you for the PR. It looks like the bucket s3://stoic2021-training does not exist...has the bucket been created yet? Or is it misnamed in this PR?

**Comment by luukboulogne** [comment]
Thank you for your message. We are currently experiencing a delay for making the training dataset publicly available: we are now switching to a new bucket in a different AWS account. Once the new bucket has been created, we would like to re-open this PR.

**Comment by luukboulogne** [comment]
The s3 bucket has been re-created. We added the "grand-challenge.org" tag as multiple future datasets to will be tied to this platform through machine learning challenges initiated by us and other parties.

**Comment by chueatwork** [comment]
Hi @luukboulogne this looks fantastic. One suggestion that I leave to you whether you want to change or not--we don't typically recommend that people provide a personal email for Contact, but rather a generic group email or even the Issues page of a GitHub repository. Mostly this avoids situations where, for example, a data provider has used their own email but then moved on to new adventures, and the user is left not knowing who to contact. Let me know if there is an email you'd want to substitute or if you'd rather have any inquiries go directly to you!

**Comment by luukboulogne** [comment]
That's great to hear. Thank you @chueatwork, also for your suggestion. I will look into what contact we can use, and will let you know when we have decided.

**Comment by luukboulogne** [comment]
Hi @chueatwork, the personal e-mail address in Contact has been changed to a generic group e-mail. If there is anything else we can do, please let me know. Thank you.

**Pull request merged**
