### PR TITLE
Adding initial nasa-soteria yaml

### PR DESCRIPTION
**Pull request by tylerfettrow**
*Issue #, if available:*

*Description of changes:*
Adding initial nasa-soteria yaml

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
Hi Tyler - did you submit a request to add this dataset to the Open Data program:  https://application.opendata.aws/. This needs to be done first, before we can process your registry entry.

**Comment by tylerfettrow** [comment]
Hi, yes I did try to add the yaml file, but I thought it was a formatting problem.

I recently learned we have to get special NASA approval before advertising this repository, so for the moment I'd like to pause the yaml uploading. I will still fill out this form so when we get approval its just a matter of submitting this pull request. At least I assume that's what I will have to do.

Thanks

Tyler

From: cstner ***@***.***>
Sent: Monday, February 5, 2024 8:01 PM
To: awslabs/open-data-registry ***@***.***>
Cc: Fettrow, Tyler D. (LARC-D318) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [awslabs/open-data-registry] Adding initial nasa-soteria yaml (PR #2112)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



@cstner requested changes on this pull request.

Hi Tyler - did you submit a request to add this dataset to the Open Data program: https://application.opendata.aws/. This needs to be done first, before we can process your registry entry.

-

**Comment by cstner** [comment]
HI Tyler - no worries - we can leave this yaml until you are ready.  NASA does have a special approval chain internally, and then you submit the request to add the dataset to the Open Data program: https://application.opendata.aws/.

**Comment by tylerfettrow** [comment]
Hi @cstner, Do you know who I can talk to about the possibility of obtaining a DOI for the data repository hosted in AWS Registry?

**Pull request closed without merging**
