### PR TITLE
Upload of Spatiam Corporation dataset

### PR DESCRIPTION
**Pull request by montilla-spatiam**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by montilla-spatiam** [comment]
Upload Spatiam Corporation NLSA ISS Experiment Data

**Review by cstner — CHANGES_REQUESTED** [review]
hi there!  have you requested that this dataset join the open data program? Or are you just looking for your data to be listed in the Regsitry?

**Comment by montilla-spatiam** [comment]
Hello! We will be hosting the data ourselves in S3 and as a NASA requirement need to publish it on an open data registry, so I believe listing it on the registry is what we are looking for. Thanks!

**Comment by cstner** [comment]
ok - great!  Can you update your branch to the latest or give us the ability to update it for you?

**Pull request merged**
