### PR TITLE
Add links to documentation on usage

### PR DESCRIPTION
**Pull request by aschroed**
Added links to documentation on 4DN on how to get files directly from open data buckets and a link to the 4DN Jupyterhub service now that it works for files that reside in the open data bucket.

### CODE REVIEW

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 1591590bbd83f08560259fdc8ba35101507c03d0
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=93512c4f-7d02-48da-b397-3881af022ff9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by chueatwork** [comment]
@aschroed can you rebase?

**Comment by aschroed** [comment]
Is that what you meant or do you need an actual rebase operation?

**Comment by chueatwork** [comment]
That's what I meant, ha. And it looks like someone just merged some more changes...so if you could just merge upstream changes again I will merge these changes ASAP. Thank you!

**Comment by aschroed** [comment]
Done.

**Pull request merged**
