### PR TITLE
Create emearth.yml

### PR DESCRIPTION
**Pull request by ShervanGharari**
The initial yml file for emearth dataset. There are empty filed that will be filled after the data upload with examples.

*Issue #, if available:* there are some fields that I left empty for later to be filled and some I am not sure such as ARN and region of the server.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
requested changes sent via email

**Comment by ShervanGharari** [comment]
I have removed the empty entries and it seems that it is compiled successfully.

**Comment by ShervanGharari** [comment]
This has passed all the checks, however, I wanted to add the related publication which caused the failure, I don't know where the issue is. We can keep this out for now from the yaml file.

```
DataAtWork:
  Publications:
    - Title: EM-Earth: The Ensemble Meteorological Dataset for Planet Earth
      URL: https://doi.org/10.1175/BAMS-D-21-0106.1
      AuthorName: Guoqiang Tang, Martyn P. Clark & Simon Michael Papalexiou
```

If there are more changes to be done please let me know.

**Review by cstner — CHANGES_REQUESTED** [review]
THis looks great but I'd recommend switching Documentation and Description info, as the text that you have in Doc is really the description and the link looks like it goes to the doc.  Does the documentation link work? it didn't resolve to anything for me.

**Comment by ShervanGharari** [comment]
Thank you, have changed the documentation and description. I think I have included the FRDR dynamic link which might change over time, so I have provided the doi for repository instead which should always work. Hope all the settled. thank you for your help.

**Review by cstner — APPROVED** [review]

**Pull request merged**
