### PR TITLE
Add yaml for nasa soho data.

### PR DESCRIPTION
**Pull request by xhagrg**
*Description of changes:*
Add YAML file for hosting the NASA SOHO/LASCO2 archival data prepared for NASA challenge through TopCoder in AWS open data registry. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by xhagrg** [comment]
@jeffejefe sounds good.

**Comment by xhagrg** [comment]
@jeffejefe I removed the tags and updated the description. Do you want me to create another PR for the tags right away?

**Comment by jeffejefe** [comment]
@xhagrg can you remove the tags.yaml file from the PR completely? It looks like your commit still has that file included. Also you might have unnecessarily removed the "machine learning" tag. Essentially anything in the current tags.yaml is fine to add if relevant. Let's hold off on the PR for tags until there is a chance for broader review.

**Comment by xhagrg** [comment]
@jeffejefe The change to tags.yaml is because i was putting them in an alphabetical order, no new tags were added. If it doesn't make sense to include it, I can have them removed.

I have now re-added `machine learning` tag.

**Comment by jeffejefe** [comment]
@xhagrg I am requesting that you remove the tags.yaml file completely from the commit as it will overwrite the one that is currently there. I'm assuming that you do not have any relevant tutorials, tools or publications to add in those sections? If there are publications related to the challenge this would be a good time to add those in. I'll merge when ready. Thanks!

**Comment by jeffejefe** [comment]
I think that both of these publications could be relevant for this dataset yaml.
[Topcoder NASA Comet Discovery: A Recap](https://www.youtube.com/watch?v=E4OxTaqTP6E)
[Winners Selected for the NASA SOHO Comet Search with Artificial Intelligence Open-Science Challenge](https://science.nasa.gov/science-news/winners-selected-for-the-nasa-soho-comet-search-with-artificial-intelligence-open-science-challenge)

**Comment by xhagrg** [comment]
@jeffejefe I restored the tags file. The current PR currently only has a new file addition.

**Pull request merged**
