### PR TITLE
Update initial Folding@home data release

### PR DESCRIPTION
**Pull request by jchodera**
*Description of changes:*

This PR refines the initial data Folding@home COVID-19 data release:
* Restrict listed buckets to those that have been populated and documented
* Refines description text
* Includes links to detailed data descriptions and instructions on the [MolSSI COVID-19 Molecular Structure and Therapeutics Hub](https://covid.molssi.org/)

Future PRs in the coming days will continue to refine the dataset description and add additional buckets as additional dataset preparation is completed.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

cc @chueatwork 

**NOTE:** The index links in here may need to be updated before merge once https://github.com/MolSSI/covid/pull/159 is merged.

### CODE REVIEW

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: e61bab5065914e15c68853a0cc620228a19e9832
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f0687a47-2680-4e40-a3de-6f507c0e1ab9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 0e8c98ed584ea2e4b300da80667a57fda5466e6a
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c3991bf6-de52-49e8-9c58-5e5a43ee3c84%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: c1c5214a649508740767cda9c3ab494409a49075
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=531903ec-b28f-4fa3-9a1a-f816208756cd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jchodera** [comment]
@chueatwork : This should be ready to merge! We'll continue to update this roughly daily this week as additional datasets are documented and added.

**Pull request merged**
