### PR TITLE
IBL Brain-wide Map

### PR DESCRIPTION
**Pull request by k1o0**
Added an initial yaml file for the International Brain Lab brain-wide map data release

### CODE REVIEW

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 07bf6e3d8c6a0d8b30b992994e27a0b0ee298d6b
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0ef78d4f-24b0-4371-9d9b-fe3d53d561db%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by chueatwork** [comment]
Hi @k1o0 this PR is failing at first glance at the tags listed; several are not currently listed here: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml

I believe our code build also distinguishes between capitalized/uncapitalized so might suggest uncapitalizing some of these!

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 056b51fbf008cf720df21a94a5bcce40a1380eb7
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ba8effcc-610a-4219-af28-f5b38e72790a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by chueatwork** [comment]
Hi @k1o0 this looks better! When you have generated the S3 buckets please update the ARNs (which is why this PR is failing codebuild). Another thing; for the "private" bucket, is this embargoed data? Is it accessible to specific collaborators? If not, let's talk about what is going to be in that bucket and whether we should even list it as a resource.

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 789108094713025ea54c13cda3fdbdaa63e006b2
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e21f72f2-7b5c-4efa-8b5c-08fa26129f7a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by chueatwork** [comment]
@k1o0 nearly there! If there are no Explore links, just delete the entire field (`Explore: NA` is failing code build).

**Comment by k1o0** [comment]
OK I've removed the explore fields.  We'll add them back in once we've restructured our public documentation.

**Pull request merged**
