### PR TITLE
Add Radiant MLHub

### PR DESCRIPTION
**Pull request by HamedAlemo**
*Issue #, if available:*

*Description of changes:*
Added a yaml file for Radiant MLHub data.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: b42ca0ebd25d86146e99282636802799ea9e9b33
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=71e6d704-3915-431b-b3b0-1b72e5eec83d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jflasher** [comment]
@HamedAlemo this is failing because you're working from an older branch (with out of date dataset listings). If you start from an up to date branch, you should be good to go.

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 8364f119eba31d0aa4bc4e32b38f9ea2f647f3f9
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0ff5746e-1ca0-44fb-aca5-323d7cf4f248%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by HamedAlemo** [comment]
Thanks @jflasher. The fail now is due to the tag `training data` we are using. Is there a way to add that to the pool of tags?

**Comment by HamedAlemo** [comment]
Hi @jflasher is there anything needed from us to merge this?

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: f09ca036a051409e6ab25aa32b8d52edab4b263c
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=54d21394-6822-497d-834d-a4beff440cf5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
