### PR TITLE
adding ucgd-gvcf yaml file

### PR DESCRIPTION
**Pull request by srynobio**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by zflamig** [comment]
@srynobio We improved our test so the error is useful. Looks like you have a trailing tab on line 36 can you fix that please? 

Also can you tweak the name? We don't need "on AWS" but it would be nice to say 1000 genomes too.

**Comment by srynobio** [comment]
The error travis is mentioning are:

```
pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
 - required.novalue : '/DataAtWork/Tutorials/0/URL'.
 - required.novalue : '/DataAtWork/Tutorials/0/AuthorName'.
 - required.novalue : '/DataAtWork/Tutorials/0/Title'.
 - required.novalue : '/DataAtWork/Tutorials/1/URL'.
 - required.novalue : '/DataAtWork/Tutorials/1/AuthorName'.
 - required.novalue : '/DataAtWork/Tutorials/1/Title'.
 - required.novalue : '/DataAtWork/Tools & Applications/0/URL'.
 - required.novalue : '/DataAtWork/Tools & Applications/0/AuthorName'.
 - required.novalue : '/DataAtWork/Tools & Applications/0/Title'.
 - required.novalue : '/DataAtWork/Publications/0/URL'.
 - required.novalue : '/DataAtWork/Publications/0/AuthorName'.
 - required.novalue : '/DataAtWork/Publications/0/Title'.: Path: '/'>
```

But in the original email I was told:

```
At this point, don't worry about the “Resources” or “DataAtWork" sections of the file; we will fill that in when you get ready to launch
```

**Comment by zflamig** [comment]
@srynobio Looks good. We will hold off merging until the data is ready and can clean up the data at work section then

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: cecd5b5458f8a0e583f25a5865730728edeee90f
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9b730355-0f70-446d-afd4-a348e3d57a6d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 91c038b0a60a1c17a309143a4614670b75877fab
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f849c19b-1ce1-453a-9d33-f8910df0d8be%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 9b73194a0767c97a759e255cb389c7702f0c8dae
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b062a1ff-b6c9-4e3a-a5d7-a46cbb536f5d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by chueatwork** [comment]
Hi @srynobio , I'm picking this up from Zac. It looks like neither of these S3 buckets exist anymore, so I'm closing this PR. Please do not hesitate to reach out if you'd like to revisit this dataset or have any other projects that could be avenues for collaboration.

**Pull request closed without merging**
