### PR TITLE
yaml file for monkey challenge

### PR DESCRIPTION
**Pull request by LindaSt**
PR to add the description yaml for the MONKEY challenge (https://monkey.grand-challenge.org/).

### CODE REVIEW

**Review by berylrab — APPROVED** [review]

**Comment by berylrab** [comment]
Hi @LindaSt, looks like the branch is out of date with the base branch and needs to be updated before I can merge it.

**Comment by LindaSt** [comment]
Hi @berylrab, I updated the branch, hope it works now!

**Comment by berylrab** [comment]
Hey Linda, unfortunately it still shows as "This branch is out-of-date with the base branch" on our end. This link could help you: https://stackoverflow.com/questions/53712930/how-to-fix-this-in-git-this-branch-is-out-of-date-with-the-base-branch

**Comment by berylrab** [comment]
Depending on the settings on your Github account, the Open Data team may be able to update the pull request directly. If the link I shared above does not work for you, please enable this feature - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork and we can try to update the branch from our end.

**Comment by LindaSt** [comment]
Hi Beryl

It is really odd because on my side, this is what I see:
image
image

I'll see if I can fix it on my end with the links you provided.

**Comment by berylrab** [comment]
Hey Linda, I see "no conflicts" on my end as well. I will work with our team to get this merged. Thank you for your patience as we work through this!

**Pull request merged**
