### PR TITLE
Add Poseidon 3D Seismic MDIO Dataset

### PR DESCRIPTION
**Pull request by tasansal**
*Description of changes:*
We are registering the dataset. We will upload the MDIO files shortly.

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
Most of the PR is fine, but please only use the tags that are already in the tags.yaml.  We typically do not add new tags unless we have several datasets that will use it, or the tags have little value.

**Comment by tasansal** [comment]
Hi @cstner, below are the new tags:

* mdio
* oil and gas
* seismic
* subsurface

The only relevant one I saw was "seismology" that we can replace "seismic" with. For the others do you have any recommended tags I can reuse?

**Review by cstner — CHANGES_REQUESTED** [review]
I would simply remove the new tags. The problem with adding new tags for each dataset is that no one else will use them, and then we have lots of tags that have little value. We highly value using the existing tags and only adding new ones sparingly and only when more than a few datasets will contain the tag.

**Comment by tasansal** [comment]
@cstner removed the extra tags, please re-review.

**Review by cstner — CHANGES_REQUESTED** [review]
One more change - please change your license from the deprecated CC BY 3.0 AU to CC BY 4.0 - see recommendation from Creative Commons: https://creativecommons.org/licenses/by/3.0/au/legalcode.en

**Comment by tasansal** [comment]
@cstner the original work (we re-formatted the SEG-Y data to MDIO) is `CC BY 3.0 AU`. Should I put the original license type in the description and license our hosted data as `CC BY 4.0`?

**Comment by cstner** [comment]
Yes that would work!

**Comment by tasansal** [comment]
done, @cstner, please re-review whenever you have a chance :)

**Comment by cstner** [comment]
that works!

**Pull request merged**
