### PR TITLE
Update to oedi-data-lake.yaml 

### PR DESCRIPTION
**Pull request by dstright**
*Issue #, if available:*
commit 3d150b6

*Description of changes:*
Added a new resource and publication to the OEDI open energy dataset yaml for dGen. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jflasher** [comment]
Hi @dstright, just a heads up it shows 0 files having been changed in this Pull Request. If you pull the latest from awslabs:master into openEDI:master, it may make it easier to see just the changes you have made (there are currently a lot of old commits showing up in the list). Or feel free to close if this was opened in error. Thanks!

**Comment by dstright** [comment]
Hi @jflasher, we updated the file in master and it's now showing. Please let us know if we need to do anything else. Thank you! Dana

**Comment by jflasher** [comment]
Thanks @dstright, looks good, but seems as though the base branch updated on our side since you did this, sorry it gets updated a lot sometimes. If you could just do one more merge from our master branch to yours, it should be good to go!

**Comment by dstright** [comment]
Hi @jflasher I merged from the master to ours. Let me know if I am on track, or need to do something else! Thanks. Dana

**Comment by zflamig** [comment]
Thanks!

**Pull request merged**
