### PR TITLE
Delete and modify AODN records

### PR DESCRIPTION
**Pull request by xhoenner**
*Issue #, if available:*

*Description of changes:*
Removing two AODN records and correcting one that had erroneous information

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
can you update this one as well - might be better to give us the ability to update for you as we'll need to update this branch once we merge the other PR

**Comment by xhoenner** [comment]
Thanks @cstner. I've updated both branches and will ask the repo owner to set the permissions so that you can do the update on your end.

**Review by cstner — CHANGES_REQUESTED** [review]
Hm. It won't let me update this branch still - but I was able to merge the other one.  Can you update this one and I'll merge it?

**Comment by xhoenner** [comment]
Done. Thanks again for your kind help @cstner!

**Comment by xhoenner** [comment]
@cstner this PR is still outstanding, would you mind having a look at it again please (I just updated the branch)?

**Comment by cstner** [comment]
looks good!

**Pull request merged**
