### PR TITLE
Cosem update

### PR DESCRIPTION
**Pull request by d-v-b**
Update the ARN for COSEM to a new bucket.

### CODE REVIEW

**Comment by chueatwork** [comment]
@d-v-b thank you for the update. Just checked s3://janelia-cosem-datasets and it appears that the bucket is not public access; could you please assign an appropriate bucket policy? Suggested policy with explanation attached.

[PDS_Bucket_Policy_Explained.pdf](https://github.com/awslabs/open-data-registry/files/4915126/PDS_Bucket_Policy_Explained.pdf)

**Comment by d-v-b** [comment]
@chueatwork Good catch! The bucket policy should be updated.

**Comment by d-v-b** [comment]
@chueatwork I've updated the bucket policy. Let me know if there's anything else missing.

**Comment by chueatwork** [comment]
Merged! Thank you @d-v-b

**Pull request merged**
