### PR TITLE
Add new entry

### PR DESCRIPTION
**Pull request by dadosabertosons**
*Issue #, if available:*

*Description of changes:*
Adding a new dataset entry

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
You need the ARNs for both buckets. You can find the ARNs on the AWS console, go to S3 service, click on the bucketname, then go to Properties, and copy the Amazon Resource Name (ARN) for the bucket and add it to this YAML.

Also - please remove the extra word "License:" on line 14

THanks!

**Comment by dadosabertosons** [comment]
Edits requested done on the file

**Review by cstner — CHANGES_REQUESTED** [review]
Almost there!  Please only use tags that are in this file: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml.  You can request that we add a tag, but we only want tags that can be used for more than 1 dataset.

**Comment by dadosabertosons** [comment]
Is there something still needing to be fixed?

**Comment by cstner** [comment]
Also – make sure the bucket is open to the public.  I’d suggest using our CloudFormation template to create the public bucket, metrics bucket, SNS topic, and bucket policies for you: https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf


From: DadosAbertos_ONS ***@***.***>
Reply-To: awslabs/open-data-registry ***@***.***>
Date: Monday, April 17, 2023 at 2:44 PM
To: awslabs/open-data-registry ***@***.***>
Cc: "Stoner (AWS), Chris" ***@***.***>, Comment ***@***.***>
Subject: Re: [awslabs/open-data-registry] Add new entry (PR #1862)


Is there something still needing to be fixed?

**Comment by dadosabertosons** [comment]
the bucket was set to public

**Review by cstner — COMMENTED** [review]
Took a few tries - but it's merging now!

**Pull request merged**
