### PR TITLE
update: including SeeFar dataset yaml: seefar.yaml

### PR DESCRIPTION
**Pull request by jameslowman**
update: including SeeFar dataset yaml: seefar.yaml

### CODE REVIEW

**Review by cstner — CHANGES_REQUESTED** [review]
Line 40 - i would suggest adding a pipe | after License: since you have multiple values for the license.

**Comment by jameslowman** [comment]
> Line 40 - i would suggest adding a pipe | after License: since you have multiple values for the license.

fixed! thanks

**Review by cstner — CHANGES_REQUESTED** [review]
Getting closer!  Now please remove any tags that aren't in the tags file here: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml and please add the tag: aws-pds

**Review by cstner — CHANGES_REQUESTED** [review]
Almost there!  Can you remove any ADX Categories that aren't in the ADX tags file here: https://github.com/awslabs/open-data-registry/blob/main/adx_categories.yaml

**Pull request merged**
