### PR TITLE
Create dataforgood-fb-forests.yaml

### PR DESCRIPTION
**Pull request by jetolan-fb**
*Description of changes:*
Added new entry for Meta / WRI Canopy Height Dataset

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jeffejefe** [comment]
@jetolan-fb apologies for the extra commits was trying to get this to a clean state for you. Feel free to add more info and I'll check it again when you're done.

**Comment by jetolan-fb** [comment]
Thanks @jeffejefe ! We are collecting all of the pieces of information, I'll update again with more of the fields filled in

**Comment by jetolan-fb** [comment]
@jeffejefe I think we are good to go, at least for this baseline yaml file. We will plan on updating over the coming weeks as more pieces fall into place.

**Comment by jetolan-fb** [comment]
Thanks @jeffejefe, that was indeed my intention!

**Pull request merged**
