### PR TITLE
Add `datasets/materials-project.yaml`

### PR DESCRIPTION
**Pull request by janosh**
@tschaume I wasn't sure what to put for `Ressources.ARN`. Do you know?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by janosh** [comment]
@tschaume Will pick this up once ready for wider release.

**Comment by tschaume** [comment]
Yes, please ignore for now. The various MP datasets are still being finalized. I'll be coordinating with my OpenData contacts at AWS and update this PR once we're getting close to publicly announcing our datasets. Thanks!

**Comment by tschaume** [comment]
PS: please also consider the distribution agreement mute/invalid. We are still in discussions internally about appropriate licenses.

**Comment by tschaume** [comment]
Can be closed. Superseded by #2002

**Pull request closed without merging**
