### PR TITLE
WIP Add 4DN to open datasets

### PR DESCRIPTION
**Pull request by aschroed**
*Issue #, if available:*

*Description of changes:*
Initial addition of the 4DN Open Dataset yaml file

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: a7658b80dbf340236802918fffa0a690e72b15ee
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3b4037bb-5d29-41f9-b92c-4ed9493eadc9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by chueatwork** [comment]
@aschroed our YAML file names have to be all lowercase--can you change over to /4dnucleome.yaml ?

**Comment by aschroed** [comment]
Done.

**Comment by chueatwork** [comment]
@aschroed please:

1. Add aws-pds to your tags (as we're sponsoring this dataset) 
2. Merge upstream changes to your branch

Thanks!! And of course add your usage examples as they become available.

Erin

**Comment by aschroed** [comment]
Still waiting on back end work before tutorials can be added.

**Comment by chueatwork** [comment]
@aschroed  We're all updating the main branch currently, sorry--please merge upstream changes and I will merge ASAP!

**Pull request merged**
