### PR TITLE
Add information for Rapid7 FDNS ANY Dataset to AWS Open Datasets

### PR DESCRIPTION
**Pull request by ssikdar-r7**

### CODE REVIEW

**Comment by jedsundwall** [comment]
@ssikdar-r7 thank you for this! Looks awesome. Can you provide a more specific URL for your "DNS Reconnaissance for $.02 using Rapid7 Open Data and AWS" post? I don't see anything related to that when I visit https://blog.rapid7.com.

**Comment by ssikdar-r7** [comment]
@jedsundwall  Hey! So marketing prefers that the blog be put on https://blog.rapid7.com after everything for public datasets goes live. I was planning to put in another pull request to update the link once that happens?

**Comment by ssikdar-r7** [comment]
Hey @jedsundwall ! 

could we possibly add back in the SNS topic section?
the topic is live but the ARN was wrong. The topic and arn are
s3-event-notification-new-aws-pds-dataset
arn:aws:sns:us-east-1:740874647437:s3-event-notification-new-aws-pds-dataset

Let me know what you think!

Thanks!

**Comment by ssikdar-r7** [comment]
Thanks!

**Pull request merged**
