### PR TITLE
Add DANDI dataset to registry

### PR DESCRIPTION
**Pull request by satra**
*Description of changes:*

Adding DANDI dataset to the open-data-registry. Our public beta for the platform is presently scheduled for March 1, 2020, alongside tutorials and documentation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

cc: @yarikoptic

### CODE REVIEW

**Comment by pschmied** [comment]
Hello @satra ,

Based on your last set of tags, I just pushed a couple of updates to them. We liked your change of "neuro imaging" to "neuroimaging" as well as your "neurophysiology" addition. Those could be added back to the Tags section if you'd like.

The only other thing I can see that is causing the tests to fail, is in the "Tools & Applications" section. For that section the format of entries should change from, e.g.:

`    - DANDI Web Interface:  https://gui.dandiarchive.org/`

to something like:

```
    - Title: DANDI Web Interface
      URL: https://gui.dandiarchive.org/
      AuthorName: DANDI Project
      AuthorURL: https://dandiarchive.org/
```

Feel free to make those modifications. Or if you'd rather, I can also make those modifications on your behalf. Just let me know—thank you!

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 51f7a22b3a8ae00110ff47a5dae8b5477bf46cc4
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=026b2949-81dc-4a38-9b34-5066aa8c09f0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by awsopendata** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: a731b6ea55511ff63ce9a6a2396e061278aeddcf
* Result: FAILED
* [Build Logs](https://ksf1fa59z7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6f63cd96-16a5-451f-9201-6f862d305ba7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by satra** [comment]
@awsopendata - this is ready for merge.

**Comment by chueatwork** [comment]
@satra my apologies for this taking so long; I am merging now and DANDI will be included in our Oct 9 launch.

**Comment by satra** [comment]
@chueatwork - thank you.

**Pull request merged**
