### PR TITLE
Create wis2-global-cache.yaml

### PR DESCRIPTION
**Pull request by 6a6d74**
*Issue #, if available:*

*Description of changes:*
Adding YAML dataset description for WIS2 Global Cache managed by Met Office and NOAA

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by 6a6d74** [comment]
@cstner - the YAML finally arrives for WIS2 Global Cache

**Comment by cstner** [comment]
the Managed By can’t take 2 providers.  You could: leave it as Met Office (and remove NOAA), but put the WMO and NOAA broader support in the description; or just put WMO instead of Met or NOAA?

**Review by cstner — CHANGES_REQUESTED** [review]
the Managed By can’t take 2 providers.  You could: leave it as Met Office (and remove NOAA), but put the WMO and NOAA broader support in the description; or just put WMO instead of Met or NOAA?

**Review by cstner — CHANGES_REQUESTED** [review]
Actually, since metoffice is the Contact for support for this dataset, why don't we set ManagedBy to Met Office and just add some text to the Description to explain that this dataset is supported by UK Met Office and NOAA.

**Comment by 6a6d74** [comment]
Changes made. Ready for review again.

**Pull request merged**
